@WebApi_HostAddress = http://localhost:5154

GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

###
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=2
Accept: application/json

###
GET {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak",
  "Email": "adam@wsei.edu.pl",
  "phone": "+48123456789"
}

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}

###
PUT {{WebApi_HostAddress}}/api/contacts/s987b09bd-6ae3-4fed-9e52-6b0dd5be305d
Content-Type: application/json

{
  "firstName": "Monika",
  "lastName": "Kowalska",
  "email" : null,
  "position" : "Intern"
}

###
POST {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes
Content-Type: application/json

{
  "content": "New note"
}
###
GET {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes
Content-Type: application/json

###