@WebApi_HostAddress = http://localhost:5154

### Wyświetlanie kontaków - błędne (brak query)
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json


### Wyświetlanie kontaków - poprawne
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=2
Accept: application/json


### Wyświetlanie osoby - poprawne
GET {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d
Accept: application/json


### Dodanie osoby - poprawne
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak",
  "Email": "adam@wsei.edu.pl",
  "phone": "+48123456789"
}


### Dodanie osoby - brak email i phone
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}


### Update osoby - poprawny
PUT {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d
Content-Type: application/json

{
  "firstName": "Monika",
  "lastName": "Kowalska",
  "email" : null,
  "position" : "Intern"
}
 


### Dodanie notatki - poprawne
POST {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes
Content-Type: application/json

{
  "content": "New note"
}

### Wyświetlanie notatek - poprawne
GET {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes
Content-Type: application/json


### Wyświetlanie notatek - błędne id osoby
GET {{WebApi_HostAddress}}/api/contacts/986b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes
Content-Type: application/json


### Usuwanie notatki - poprawne
DELETE {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes/33ac023b-6207-4e8f-b4e3-74aad3abb605


### Usuwanie notatki - błędne id osoby
DELETE {{WebApi_HostAddress}}/api/contacts/986b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes/e0741102-b179-4dba-a301-a7200d9f2281


### Usuwanie notatki - błędne id notatki
DELETE {{WebApi_HostAddress}}/api/contacts/987b09bd-6ae3-4fed-9e52-6b0dd5be305d/notes/b6505dce-3ff5-446b-a82d-5e1094c3ee1c