@WebApi_HostAddress = http://localhost:5154

### Logowanie do kontrolera Auth - poprawne
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@crm.pl",
  "password": "Manager@123!"
}

### Dodanie interakcji email - poprawne
POST {{WebApi_HostAddress}}/api/interactions/contacts/3f1bab9c-dc9c-475b-b281-755e3a23b150/email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


{
  "date": "2026-05-17T14:00:00",
  "content": "Wysłano ofertę do klienta",
  "emailAddress": "klient@test.pl",
  "subject": "Oferta współpracy"
}


### Dodanie sms - poprawne
POST {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/sms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


{
  "date": "2026-05-17T15:00:00",
  "content": "Wysłano SMS z przypomnieniem",
  "phoneNumber": "+48123456789"
}


### Dodanie spotkania - poprawne
POST {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/meeting
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


{
  "date": "2026-05-18T10:00:00",
  "content": "Spotkanie z klientem",
  "location": "Kraków",
  "durationMinutes": 60
}


### Dodanie interakcji sms - nieprawidłowe id
POST {{WebApi_HostAddress}}/api/interactions/contacts/adc25ac1-7e05-47c4-9049-c6c89e7b8f9c/sms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


{
  "date": "2026-05-17T15:00:00",
  "content": "Test blednego id",
  "phoneNumber": "+48123456789"
}


### Dodanie sms - za długi numer telefonu
POST {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/sms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU

{
  "date": "2026-05-17T15:00:00",
  "content": "Test za długiego numeru telefonu",
  "phoneNumber": "+48123456789123456789123456789"
}


### Dodanie email - brak wymaganego emaila
POST {{WebApi_HostAddress}}/api/interactions/contacts/3f1bab9c-dc9c-475b-b281-755e3a23b150/email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU

{
  "date": "2026-05-17T14:00:00",
  "content": "Test braku adresu email",
  "subject": "Brak emaila"
}


### Wyświetlanie interakcji klienta - poprawne
GET {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie interakcji po zakresie dat - poprawne
GET {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/dates?from=2026-05-18&to=2030-12-31
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU



### Wyświetlanie interakcji po typie - poprawne
GET {{WebApi_HostAddress}}/api/interactions/contacts/3f1bab9c-dc9c-475b-b281-755e3a23b150/type/Email
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie interakcji po typie - błędny typ
GET {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/type/PhoneCall
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie wszystkich interakcji stronicowane - poprawne
GET {{WebApi_HostAddress}}/api/interactions?page=1&size=4
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie interakcji po typie SMS - poprawne
GET {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/type/Sms
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie interakcji po id - poprawne
GET {{WebApi_HostAddress}}/api/interactions/f6016857-ccf4-4d4e-88eb-59d59349579a
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie interakcji po id - błędne id
GET {{WebApi_HostAddress}}/api/interactions/00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Wyświetlanie interakcji - nieprawidłowe id osoby
GET {{WebApi_HostAddress}}/api/interactions/contacts/adc25ac1-7e05-47c4-9049-c6c89e7b8f9c
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Update interakcji - poprawny
PUT {{WebApi_HostAddress}}/api/interactions/f6016857-ccf4-4d4e-88eb-59d59349579a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


{
  "content": "Zaktualizowana treść interakcji",
  "emailAddress": "updated@test.pl",
  "subject": "Zmieniony temat"
}


### Update interakcji - błędne id
PUT {{WebApi_HostAddress}}/api/interactions/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


{
  "content": "Próba aktualizacji nieistniejącej interakcji"
}


### Usuwanie interakcji - poprawne
DELETE {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/5ba5987a-f09b-48c1-b87a-edc387a07203
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Usuwanie interakcji - błędne id interakcji
DELETE {{WebApi_HostAddress}}/api/interactions/contacts/937348fd-7f13-4b8f-9c28-bb13639cf13c/00000000-0000-0000-0000-000000000000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU




### Wyświetlanie kontaków - błędne (brak query)
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json


### Wyświetlanie kontaków - poprawne
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=4
Accept: application/json


### Wyświetlanie osoby - poprawne
GET {{WebApi_HostAddress}}/api/contacts/adc15ac1-7e05-47c4-9049-c6c89e7b8f9c
Accept: application/json


### Dodanie osoby - poprawne
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Grzegorz",
  "lastName" : "Nowinski",
  "Email": "grzegorz@wsei.edu.pl",
  "phone": "+48123456789"
}


### Dodanie osoby - brak email i phone
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}


### Update osoby - poprawny
PUT {{WebApi_HostAddress}}/api/contacts/adc15ac1-7e05-47c4-9049-c6c89e7b8f9c
Content-Type: application/json

{
  "firstName": "Monika",
  "lastName": "Kowalska",
  "email" : null,
  "position" : "Intern"
}
 


### Dodanie notatki - poprawne
POST {{WebApi_HostAddress}}/api/contacts/adc15ac1-7e05-47c4-9049-c6c89e7b8f9c/notes
Content-Type: application/json

{
  "content": "New note"
}

### Wyświetlanie notatek - poprawne
GET {{WebApi_HostAddress}}/api/contacts/adc15ac1-7e05-47c4-9049-c6c89e7b8f9c/notes
Content-Type: application/json


### Wyświetlanie notatek - błędne id osoby
GET {{WebApi_HostAddress}}/api/contacts/adc25ac1-7e05-47c4-9049-c6c89e7b8f9c/notes
Content-Type: application/json


### Usuwanie notatki - poprawne
DELETE {{WebApi_HostAddress}}/api/contacts/adc15ac1-7e05-47c4-9049-c6c89e7b8f9c/notes/33ac023b-6207-4e8f-b4e3-74aad3abb605


### Usuwanie notatki - błędne id osoby
DELETE {{WebApi_HostAddress}}/api/contacts/adc15ac2-7e05-47c4-9049-c6c89e7b8f9c/notes/e0741102-b179-4dba-a301-a7200d9f2281


### Usuwanie notatki - błędne id notatki
DELETE {{WebApi_HostAddress}}/api/contacts/adc15ac1-7e05-47c4-9049-c6c89e7b8f9c/notes/b6505dce-3ff5-446b-a82d-5e1094c3ee1c


### Zapytanie z tokenem - poprawne
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=5
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3MmM0YjA4LWQ0NzctNGUxMC05NjBjLTc0M2I4MTc0YmE5MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU3ByemVkYcW8IiwianRpIjoiZDAxZDhjZDItZTIyNS00NzQ1LTgyMzEtOGQ2MWZmMDRhNWVmIiwiaWF0IjoiMTc3Njc4NjU5MCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NzY3ODY1OTAsImV4cCI6MTc3Njc5MDE5MCwiaXNzIjoiSWRlaXNDcm1BcGkiLCJhdWQiOiJDcm1DbGllbnQifQ.qTARJ3anK80f8PV2w_jKUpsWcEed3vXzbeC9eekLfWU


### Zapytanie bez tokenu - błedne
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json
